### ISSUE TITLE
clash

### ISSUE THREAD

**Issue by pranavbhuv** [jojoe77777/FormAPI#12]
Two, plugins, that both use FormAPI, clash with each other. So you  get wrong UIs for each

**Comment by SuperKali** [comment]
same problem for me @QuiverlyRivalry fix please @jojoe77777

**Comment by tbnritzdoge** [comment]
I have two plugins that use FormAPI and they now dont work at all.

**Comment by tbnritzdoge** [comment]
@jojoe77777 Please fix
