### ISSUE TITLE
BUG in 1.2.5

### ISSUE THREAD

**Issue by pranavbhuv** [jojoe77777/FormAPI#14]
Okay, I did some research and found some bugs which are happening because of 1.2.5.
1. Two Plugins, depending on FormsAPI, will conflict
2. Wont send commands, when click button wont carry out task.
Id be grateful if you find a fix to this @jojoe77777 or @dktapps 
Thanks

**Comment by SuperKali** [comment]
Same problem

**Comment by pranavbhuv** [comment]
You seem like a reputable developer. Do you think you can PR? Is the packets glitching or something..?
