### ISSUE TITLE
Can't send a form from a form.

### ISSUE THREAD

**Issue by HittmanA** [jojoe77777/FormAPI#21]
Whenever I try to send a form when a button in another form is clicked, it does nothing but close the current form. No errors in console either. Is this because of the latest update? If so, how do I send a form once another form button is clicked?

**Comment by SOF3** [comment]
Perhaps you should show your code.

**Comment by jojoe77777** [comment]
Works perfectly for me. 


> Perhaps you should show your code.

**Comment by HittmanA** [comment]
https://pastebin.com/Gpz5uJvB

**Comment by jojoe77777** [comment]
You haven't updated your code to reflect the changes in #20.
`$data` for a simple form is now directly an int or null
(replace all references to `$data[0]` with `$data` for simple forms)

**Comment by HittmanA** [comment]
Thanks, I didn't look at the commit changes.
