### ISSUE TITLE
give me a hand,guys

### ISSUE THREAD

**Issue by zhangbeic** [jojoe77777/FormAPI#31]
Where is it wrong?Can you give an example of the connected interface for me?
Thanks!

$formapi = $this->getServer()->getPluginManager()->getPlugin("FormAPI");
			$form = $formapi->createSimpleForm(function ($player,array $data = null){
	if($data === null){
        return;
        }
				switch($data[0]){
						case 0:
					$this->getServer()->getCommandMap()->dispatch($player, "tjoin");;
						break;
						case 1:
						$this->tsetForm($player);
						break;
						case 2:
						$this->getServer()->getCommandMap()->dispatch($player, "tquit");
						}
		});
	
			$form->setTitle("§l§7Trad §bMenu");
			$form->setContent("§o§a);
			$form->addButton("§l§6);
			$form->addButton("§l§6进入交易模式");
			$form->addButton("§l§6设置交易价格");
						$form->addButton("§l§6退出交易模式");
			
			$form->sendToPlayer($player);

**Comment by jojoe77777** [comment]
The issue tracker is not for support with your own code (even if using FormAPI)
