### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by ctw452002** [jojoe77777/FormAPI#35]
Image at FormAPI take 30seconds+ to load plz help

 $form->addButton("RED",1, "https://d1u5p3l4wpay3k.cloudfront.net/minecraft_gamepedia/thumb/7/70/Red_Wool.png/150px-Red_Wool.png?version=cedef5f2b12d3e9171914c8a9c9654e4");

**Comment by jojoe77777** [comment]
Client issue
