### ISSUE TITLE
Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent

### ISSUE THREAD

**Issue by kitkung2411** [jojoe77777/FormAPI#37]
Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'FormAPI v1.2.0': Argument 2 passed to ShopUI\Main::ShopUI\{closure}() must be of the type array, null given, called in C:\Users\cw\Desktop\1.5.0\plugins\FormAPI-master\src\jojoe77777\FormAPI\FormAPI.php on line 75 on jojoe77777\FormAPI\FormAPI
23:12:11 CRITICAL > TypeError: "Argument 2 passed to ShopUI\Main::ShopUI\{closure}() must be of the type array, null given, called in C:\Users\cw\Desktop\1.5.0\plugins\FormAPI-master\src\jojoe77777\FormAPI\FormAPI.php on line 75" (EXCEPTION) in "plugins/WolfGangShopUI-master/src/ShopUI/Main" at line 67

**Comment by dktapps** [comment]
duplicate of #23 ... please check closed issues before opening a new one
