### ISSUE TITLE
Check text in input after clicking button

### ISSUE THREAD

**Issue by JanGlukhovsky** [jojoe77777/FormAPI#5]
How can I check if text in input was changed and what's the text after clicking Button?

I've tried this, but it don't work

  ` $api = $this->plugin->getServer()->getPluginManager()->getPlugin("FormAPI");
        $form = $api->createCustomForm(function(Player $player, array $data){
            $result = $data[0];
                     if($result["input"]["text"] == "Hi"){
                    $player->sendMessage("test");
            }

        });
       $form->addInput("Test", "idk", "Type random message here");
       $format->addButton("Sumbit");`

**Comment by jojoe77777** [comment]
If you can't use this API by yourself, wait for the PMMP form api
