### ISSUE TITLE
Not working so well

### ISSUE THREAD

**Issue by lightyisreal** [jojoe77777/FormAPI#62]
When I click a button of the form, it does nothing.
Server Software: PocketMine 3.13.0

**Comment by dktapps** [comment]
a bad workman blames his tools and doesn't show the work...

**Comment by lightyisreal** [comment]
Ok ok, this is the code: https://hastebin.com/rofiforesa.xml

**Comment by Arcoz0308** [comment]
@ItzLightyHD tri to doe case "0":

**Comment by lightyisreal** [comment]
> 
> 
> @ItzLightyHD tri to doe case "0":

It doesn't happen only with my plugins, but with most of the FormAPI plugins not made by me
