### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Shadow-87** [jojoe77777/FormAPI#67]
Hello the pro guys!
Can you help me, how can I use this plugin?

**Comment by 0x470** [comment]
This is a Simple API for making forms and is only for PocketMine-MP.You can look up tutorials on making a form plugin.There are a lot of tutorials that are great. By the way this plugin has no commands.

**Comment by Shadow-87** [comment]
Thank you

**Comment by Shadow-87** [comment]
Thank you
