### ISSUE TITLE
Call to an undefined method pocketmine\plugin\Plugin::createSimpleForm()

### ISSUE THREAD

**Issue by Kylan1940** [jojoe77777/FormAPI#68]
public function OnlineUI($player){
	  $api = $this->getServer()->getPluginManager()->getPlugin("FormAPI");
    $form = $api->createSimpleForm (function (Player $player, int $data = null) {
        $result = $data;
        if($result === null){
            return true;
			}
		});

Bruh, Why??

**Comment by soyilai** [comment]
you installed the plugin correctly?

**Comment by Kylan1940** [comment]
> you installed the plugin correctly? 

Done

$this->getServer()->getPluginManager()->getPlugin("FormAPI");

But doesn't work
